name = "meet-signaling"
main = "src/index.ts"
compatibility_date = "2024-03-03"

[durable_objects]
bindings = [
  { name = "WEBRTC_SIGNALING", class_name = "WebRTCSignaling" }
]

[[migrations]]
tag = "v1"
new_classes = ["WebRTCSignaling"]
